name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Bump version, generate CHANGELOG and create GitHub release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: simple
